apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "buckethub.fullname" . }}
  labels:
    {{- include "buckethub.labels" . | nindent 4 }}
data:
  BASE_URL: {{ required "config.baseUrl is required" .Values.config.baseUrl | quote }}
  PORT: {{ .Values.config.port | quote }}
  DB_CONNECTION_STRING: {{ .Values.config.dbConnectionString | quote }}
  AUTH_RATE_LIMIT: {{ .Values.config.authRateLimit | quote }}
  RPC_RATE_LIMIT: {{ .Values.config.rpcRateLimit | quote }}
  {{- if .Values.config.admin.email }}
  ADMIN_EMAIL: {{ .Values.config.admin.email | quote }}
  {{- end }}
  {{- if .Values.config.admin.name }}
  ADMIN_NAME: {{ .Values.config.admin.name | quote }}
  {{- end }}
