{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buckethub.fullname" . }}
  labels:
    {{- include "buckethub.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_ENCRYPTION_KEY: {{ required "secrets.secretEncryptionKey is required" .Values.secrets.secretEncryptionKey | b64enc | quote }}
  AUTH_SECRET: {{ required "secrets.authSecret is required" .Values.secrets.authSecret | b64enc | quote }}
  {{- if .Values.secrets.adminPassword }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.smtp.host }}
  SMTP_HOST: {{ .Values.secrets.smtp.host | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.smtp.port }}
  SMTP_PORT: {{ .Values.secrets.smtp.port | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.smtp.user }}
  SMTP_USER: {{ .Values.secrets.smtp.user | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.smtp.password }}
  SMTP_PASS: {{ .Values.secrets.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.smtp.from }}
  SMTP_FROM: {{ .Values.secrets.smtp.from | b64enc | quote }}
  {{- end }}
{{- end }}
